'use client';

import React, { useState } from 'react';
import { Button, Modal } from 'react-bootstrap'; 
import { ChatDotsFill } from 'react-bootstrap-icons';
import PropTypes from 'prop-types';

const CarouselCommentary = ({ comments, model }) => {

    const [show, setShow] = useState(false);

    const handleClose = () => setShow(false);
    const handleShow = () => setShow(true);

    return (
        <div className='p-3'>
            <div className="card border-0 shadow-sm">
                <div className="card-header bg-white border-0">
                    <div className="d-flex align-items-center justify-content-between">
                        <div>
                            <h6 className="mb-0 fw-semibold">AI Commentary</h6>
                            <small className="text-muted">Generated by {model}</small>
                        </div>
                        <Button 
                            variant="outline-primary" 
                            size="sm"
                            onClick={handleShow}
                            className="d-flex align-items-center gap-1"
                        >
                            <ChatDotsFill />
                            <span className="d-none d-md-inline">Full Text</span>
                        </Button>
                    </div>
                </div>
                <div className="card-body" style={{ minHeight: '120px', maxHeight: '120px', overflow: 'hidden' }}>
                    <div className="d-flex flex-column gap-2">
                        <cite className="text-secondary fst-normal">
                            <div className="d-none d-lg-block">{comments.comment}</div>
                            <div className="d-lg-none">{comments.comment.slice(0, 120)}...</div>
                        </cite>
                        {comments.audio && (
                            <audio 
                                controls 
                                src={comments.audio} 
                                className="w-100" 
                                style={{ maxHeight: '32px' }}
                            />
                        )}
                    </div>
                </div>
            </div>

            <Modal show={show} onHide={handleClose} centered>
                <Modal.Header closeButton>
                    <Modal.Title>Full AI Commentary</Modal.Title>
                </Modal.Header>
                <Modal.Body>
                    <p className="mb-0">{comments.comment}</p>
                </Modal.Body>
                <Modal.Footer className="d-flex justify-content-between">
                    <small className="text-muted">Generated on {comments.date}</small>
                    <Button variant="primary" onClick={handleClose}>
                        Close
                    </Button>
                </Modal.Footer>
            </Modal>
        </div>
    );
};

CarouselCommentary.propTypes = {
    comments: PropTypes.object.isRequired,
    model: PropTypes.string.isRequired,
};

export default CarouselCommentary;
